//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sphelper_try1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prerequisite
    {
        public int Id { get; set; }
        public string SubjectCode { get; set; }
        public string Extra { get; set; }
    
        public virtual prerequisite_combination prerequisite_combination { get; set; }
        public virtual subject subject { get; set; }
    }
}
