//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sphelper_try1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prerequisite_combination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prerequisite_combination()
        {
            this.prerequisites = new HashSet<prerequisite>();
        }
    
        public int Id { get; set; }
        public string StudyPlanCode { get; set; }
        public string SubjectCode { get; set; }
        public string Combination_Id { get; set; }
    
        public virtual combination_operator combination_operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prerequisite> prerequisites { get; set; }
        public virtual studyplan_subject studyplan_subject { get; set; }
    }
}
