//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sphelper_try1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studyplan_qualification
    {
        public string StudyPlanCode { get; set; }
        public string QualCode { get; set; }
        public int Priority { get; set; }
    
        public virtual qualification qualification { get; set; }
    }
}
