//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sphelper_try1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.student_grade = new HashSet<student_grade>();
            this.student_studyplan = new HashSet<student_studyplan>();
        }
    
        public string StudentID { get; set; }
        public string GivenName { get; set; }
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter Email Address.")]
        public string EmailAddress { get; set; }


        [Required(ErrorMessage = "Please enter Password.")]
        //[("Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_grade> student_grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_studyplan> student_studyplan { get; set; }
    }
}
